version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb:mongodb+srv://yashdevops2009_db_user:Gn6fcRuIK5ZadMVp@yash.x79gyn0.mongodb.net/
    depends_on:
      - mongo

  frontend-blue:
    build: ./frontend-blue
    ports:
      - "3100:3100"

  frontend-green:
    build: ./frontend-green
    ports:
      - "3200:3200"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
